{{- $services := .Values.services -}}
{{- range $name, $svc := $services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
  selector:
    app: {{ $name }}
---
{{- end }}
