[allowlist]
description = "Allowlist"
paths = [
    '''package-lock.json$''',
    '''yarn.lock$''',
    '''.svg$'''
]

[rules]
    [rules.npm-auth-token]
    description = "npm Auth Token"
    regex = '''//registry.npmjs.org/:_authToken=[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'''
    tags = ["npm", "auth", "token"]

    [rules.aws-access-key]
    description = "AWS Access Key ID"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["aws", "credentials"]

    [rules.aws-secret-key]
    description = "AWS Secret Access Key"
    regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
    tags = ["aws", "credentials"]

    [rules.github-pat]
    description = "GitHub Personal Access Token"
    regex = '''ghp_[0-9a-zA-Z]{36}'''
    tags = ["github", "token"]

    [rules.private-key]
    description = "Private Key"
    regex = '''-----BEGIN ((RSA|DSA|EC|PGP|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
    tags = ["key", "private"]