apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: messaging-service
        image: ghcr.io/dhruvpatel50/messaging-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: messaging-service-secrets
              key: mongodb-uri
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: CLIENT_URL
          value: "http://frontend:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP