name: Build and Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'services/**'
      - '.github/workflows/build-and-push.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, user-service, swap-service, messaging-service, feedback-service]

    env:
      OWNER: ${{ github.repository_owner.toLowerCase() }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Print resolved owner and tags (debug)
      run: |
        echo "OWNER=${{ env.OWNER }}"
        echo "IMAGE_TAG=ghcr.io/${{ env.OWNER }}/skillswapper-${{ matrix.service }}:${{ github.sha }}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./services/${{ matrix.service }}
        push: true
        tags: |
          ghcr.io/${{ env.OWNER }}/skillswapper-${{ matrix.service }}:${{ github.sha }}
          ghcr.io/${{ env.OWNER }}/skillswapper-${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max