name: CI / CD Pipeline with DevSecOps

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write
  security-events: write

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.sha }}

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create results directory
        run: mkdir -p results

      - name: Gitleaks Scanner
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          config-path: .gitleaks.toml
          report-format: sarif
          report-path: results/gitleaks.sarif
        continue-on-error: true

      - name: List results directory (Debug)
        if: always()
        run: ls -la results/

      - name: Upload Gitleaks Report
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('results/gitleaks.sarif') != ''
        with:
          sarif_file: results/gitleaks.sarif
          category: gitleaks
          wait-for-processing: true

  build-and-test:
    name: Build, Test & Security Scan
    needs: security-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, feedback-service, messaging-service, swap-service, user-service]
    steps:
      - name: Set lowercase owner
        run: echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./services/${{ matrix.service }}
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci --silent
            else
              npm install --silent
            fi
          fi

      - name: Run NPM Audit
        working-directory: ./services/${{ matrix.service }}
        run: |
          if [ -f package.json ]; then
            npm audit --audit-level=high --json > npm-audit.json || true
          fi

      - name: Run ESLint
        working-directory: ./services/${{ matrix.service }}
        run: |
          if [ -f package.json ]; then
            npm install --save-dev eslint eslint-plugin-security
            npx eslint . --format=sarif --output-file=eslint.sarif || true
          fi

      - name: Upload ESLint Report
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('./services/${{ matrix.service }}/eslint.sarif') != ''
        with:
          sarif_file: ./services/${{ matrix.service }}/eslint.sarif
          category: eslint
          wait-for-processing: true

      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk.sarif
        continue-on-error: true

      - name: Upload Snyk Report
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('snyk.sarif') != ''
        with:
          sarif_file: snyk.sarif
          category: snyk
          wait-for-processing: true

      - name: Run tests
        working-directory: ./services/${{ matrix.service }}
        run: |
          if [ -f package.json ]; then
            npm test --silent || true
          fi

  build-and-push:
    name: Build, Scan & Push Docker Images
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, feedback-service, messaging-service, swap-service, user-service]
    steps:
      - name: Set lowercase owner
        run: echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build image for scanning
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          load: true
          tags: ${{ matrix.service }}:${{ github.sha }}
          file: ./services/${{ matrix.service }}/Dockerfile

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.service }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('trivy-results.sarif') != ''
        with:
          sarif_file: trivy-results.sarif
          category: trivy
          wait-for-processing: true

      - name: Build and push final image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}
          file: ./services/${{ matrix.service }}/Dockerfile

  terraform:
    name: Terraform (init / plan / apply)
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' && (
        contains(join(github.event.commits.*.added, ' '), 'infra/') ||
        contains(join(github.event.commits.*.modified, ' '), 'infra/') ||
        contains(join(github.event.commits.*.removed, ' '), 'infra/')
      ) || github.event_name == 'pull_request'
    env:
      TF_ROOT: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_ROOT }}
        run: |
          terraform plan -input=false -no-color -out=tfplan || true
          terraform show -no-color tfplan > plan.txt || true
          echo "PLAN<<EOF" >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Plan on PR (optional)
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Terraform plan for ${{ github.ref }}:
            ${{ steps.plan.outputs.PLAN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -auto-approve
