name: CI - build and push images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ auth-service, user-service, swap-service, messaging-service, feedback-service ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print resolved owner and tags (debug)
        run: |
          echo "OWNER=${{ env.OWNER }}"
          echo "IMAGE_TAG=ghcr.io/${{ env.OWNER }}/${{ matrix.service }}:${{ github.sha }}"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set owner env
        run: echo "OWNER=${{ github.repository_owner.toLowerCase() }}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ matrix.service }}:${{ github.sha }}
            ghcr.io/${{ env.OWNER }}/${{ matrix.service }}:latest

      - name: Output pushed image
        run: echo "pushed ghcr.io/${{ env.OWNER }}/${{ matrix.service }}:${{ github.sha }}"
